insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (1, PARSEDATETIME('2021-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'FOOTBALL',3 ,'BJK-FB');

insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (2, PARSEDATETIME('2021-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'FOOTBALL',2 ,'BJK-GS');

insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (3, PARSEDATETIME('2021-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'FOOTBALL',2 ,'BJK-TS');

insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (4, PARSEDATETIME('2021-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'FOOTBALL',2 ,'BJK-ANT');

insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (5, PARSEDATETIME('2021-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'FOOTBALL',2 ,'BJK-GOZ');

insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (6, PARSEDATETIME('2021-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'FOOTBALL',1 ,'BJK-SIV');

insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (7, PARSEDATETIME('2019-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'FOOTBALL',1 ,'BJK-DEN');

insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (8, PARSEDATETIME('2021-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'FOOTBALL',1 ,'BJK-BAS');

insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (9, PARSEDATETIME('2021-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'BASKETBALL',1 ,'BJK-EFES');

insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (10, PARSEDATETIME('2021-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'BASKETBALL',2 ,'BJK-KARSIYAKA');

insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (11, PARSEDATETIME('2021-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'BASKETBALL',2 ,'BJK-ULKER');

insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (12, PARSEDATETIME('2021-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'BASKETBALL',2 ,'BJK-GS');

insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (13, PARSEDATETIME('2021-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'BASKETBALL',3 ,'BJK-TOFAS');

insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (14, PARSEDATETIME('2021-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'TENNIS',1 ,'Nadal-Federer');

insert into EVENT(ID, EVENT_DATE, TYPE,MBS,NAME) values (15, PARSEDATETIME('2021-12-10 22:00', 'YYYY-MM-dd HH:mm'), 'TENNIS',1 ,'Nadal-Djokovic');